name: Build and Test

# Run this action on pull requests (or commits pushed to PRs) and merge to main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - 'main'  # Triggers on PRs against any branch

# Define jobs that need to be run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # You can change the version as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Lint the code
      - name: Run npm lint
        run: npm run lint

      # Step 5: Run the build script
      - name: Run npm build
        run: npm run build
